#!/bin/bash
case $1 in
    run)
        java -jar ../lib/stop-streamer.jar "$2"
        ;;
    start)
        if [[ -f /tmp/.stop-streamer-pid ]] ; then
            exit 1
        fi
        java -jar ../lib/stop-streamer.jar "$2" &
        echo $! >/tmp/.stop-streamer-pid
        ;;
    stop)
        if [[ ! -f /tmp/.stop-streamer-pid ]]; then
            exit 1
        fi
        kill -9 $(cat /tmp/.stop-streamer-pid)
        rm /tmp/.stop-streamer-pid
        ;;
    *)
        exit 1
        ;;
esac
